Fix for gnome 41.3 (pop & ubuntu 22.04)
RensAlthuis/vertical-overview pull request #101
Opened 2022-03-15 20:25 UTC by 13r0ck

- use the correct protoype
Caused by gnome javascript PR: https://gitlab.gnome.org/GNOME/gjs/-/commit/e74701596c2ff9880cd39289b9649bb490951091#03566cbfedf849175708a56bfbbc92fe4cd7a28f

- merge upstream changes
Caused by gnome-shell PR: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/5d1d4b56c6a804aec324ca8e97f7e045ce49e958

2022-03-30 04:42 UTC, Gronkdalonka commented
This fix does work on Gnome 41.4

2022-03-30 09:02 UTC, atd commented
Thank you for this :heart:

2022-03-30 12:08 UTC, jm-duke commented
The fix is not complete, as it crashes the extension, when e.g. the lock screen activates:

`gnome-shell[2341]: JS ERROR: Extension vertical-overview@RensAlthuis.github.com: TypeError: WorkspacesView.SecondaryMonitorD
isplay is undefined#012reset@`

The reset() method still references WorkspacesView.SecondaryMonitorDisplay, which is no longer there. Removing this reference seems to work fine, no more crashes on my end.

```
@@ -26,7 +23,6 @@ function override() {
 
 function reset() {
     Util.overrideProto(WorkspacesView.WorkspacesView.prototype, global.vertical_overview.GSFunctions['WorkspacesView']);
-    Util.overrideProto(WorkspacesView.SecondaryMonitorDisplay.prototype, global.vertical_overview.GSFunctions['SecondaryMonitorDisplay']);
     if (global.vertical_overview.default_old_style_enabled) {
         Main.overview._overview._controls._workspacesDisplay.remove_style_class_name("vertical-overview");
     }
```

2022-03-31 17:02 UTC, 13r0ck commented
This has been change to hopefully fix 
https://github.com/RensAlthuis/vertical-overview/pull/101#issuecomment-1083059270
& https://github.com/RensAlthuis/vertical-overview/issues/98#issuecomment-1084227148

2022-04-03 19:38 UTC, maxmorozoff approved these changes
It works. Thanks!

2022-04-06 07:10 UTC, RensAlthuis requested changes
Thank you so much! I do have some small requests, but then I'll merge and publisher as soon as I can.

2022-04-06 07:10 UTC, RensAlthuis commented on metadata.json
> +        "41",
Pretty sure this will break the extension for 40 and 41.
I am ok with that, supporting older versions is way too much effort. However since gnome forces people to the latest version of an extension we can't leave the old ones in here.

2022-04-06 21:02 UTC, 13r0ck commented on workspacesView.js
> +    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason.\nSecondaryMonitorDisplay = ' + WorkspacesView.SecondaryMonitorDisplay + '\nSince I\'m overriding val
Strangely enough this is required. I think it might be some GJS bug, but without printing `WorkspacesView.SecondaryMonitorDisplay` the use of it doesn't work in the next line saying that it cant be found.

2022-04-06 21:02 UTC, 13r0ck commented on workspacesView.js
> +}
:+1:

2022-04-06 21:02 UTC, 13r0ck commented on metadata.json
> +        "41",
:+1:

2022-04-09 10:46 UTC, RensAlthuis commented on workspacesView.js
> +    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason.\nSecondaryMonitorDisplay = ' + WorkspacesView.SecondaryMonitorDisplay + '\nSince I\'m overriding val
```suggestion
    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason\nSince I\'m overriding values in that const an error show might show up.\n Feel free to ignore it');
    SecondaryMonitorDisplay = WorkspacesView.SecondaryMonitorDisplay;

```

2022-04-09 10:47 UTC, RensAlthuis commented on workspacesView.js
> +    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason.\nSecondaryMonitorDisplay = ' + WorkspacesView.SecondaryMonitorDisplay + '\nSince I\'m overriding val
This works too, and it doesn't fill up the journal

2022-04-09 18:39 UTC, 13r0ck commented on workspacesView.js
> +    log('You may see an error below,\nSecondaryMonitorDisplay is defined as const for some reason.\nSecondaryMonitorDisplay = ' + WorkspacesView.SecondaryMonitorDisplay + '\nSince I\'m overriding val
Good catch! Thanks!

2022-04-10 10:09 UTC, merged

2022-04-12 15:38 UTC, neclimdul commented
manually installing this and getting my mental desktop management back in the  groove today was the highlight of my morning. thanks for all the work y'all.

2022-04-16 05:28 UTC, axxapy commented
@RensAlthuis This PR was merged but issue described in https://github.com/RensAlthuis/vertical-overview/pull/101#issuecomment-1084872250 is still there.
Only way to fix: `git checkout 02bf3c4a646037ad65423a23d728108bcc9a892a -- overviewControls.js`