Restore thumbnails wallpapers
RensAlthuis/vertical-overview pull request #6
Opened 2021-04-08 01:58 UTC by romgrk

So basically I reverted [this commit where they removed the wallpapers](https://github.com/GNOME/gnome-shell/commit/451ba5b03ad714366cb0ce6105cb775f84b051ba), and it works.

2021-04-10 11:42 UTC, RensAlthuis commented
Thanks for doing this! But do we really need to overwrite all these methods in order to get this working? I feel like there might be an easier way. Also please limit the changes to just whatever is necessary for the thumbnails background.

2021-04-13 16:18 UTC, axxapy commented
I just wanted to say thank you to @romgrk for pointing on this commit https://github.com/GNOME/gnome-shell/commit/451ba5b03ad714366cb0ce6105cb775f84b051ba

Thanks to you I was able to restore wallpaper on thumbnails in my extension (https://github.com/axxapy/gnome-ui-tune/commit/6a853761f13c628aa816cfa1fa097cea7ccd6734)

<img src=https://user-images.githubusercontent.com/3088476/114586043-3e376080-9c52-11eb-92a9-94c3f31fe84c.png width=800>

2021-04-13 16:58 UTC, romgrk commented
Update PR to integrate changes that were done on master. I've removed the stacking code.

2021-04-14 16:52 UTC, RensAlthuis requested changes
Nice! This looks a lot better. I still have some small remarks though.

2021-04-14 16:52 UTC, RensAlthuis commented on util.js
> +            };
Careful here, this won't reset properly when the extension is disabled. When rrestoring the backup the symbol will be ``after__init`` instead ``of _init``
I think moving
```js
backup[symbol] = proto[symbol];
``` 
into the if statements, and for the `after_` case something like:
```js
backup[symbol] = fn;
```
is enough to fix it

2021-04-14 16:52 UTC, RensAlthuis commented on workspaceThumbnail.js
> +    },
- The Background manager already takes care of adding a background actor, adding it manually will cause errors (also add_actor is deprecated, it should be add_child now).
- Overwriting ``_onDestroy`` does not work since it is bound in ``WorkspaceThumbnail``'s init so we'll have to add an extra callback on the signal.

I think we can replace the whole thing with:
```suggestion
    after__init: function () {
        this._bgManager = new Background.BackgroundManager({
            monitorIndex: Main.layoutManager.primaryIndex,
            container: this._contents,
            vignette: false
        });

        this.connect('destroy', (function () {
            this._bgManager.destroy();
            this._bgManager = null;
        }).bind(this));
    }
```

2021-04-14 21:58 UTC, romgrk commented
Both remarks addressed, let me know if there is anything else to be done here.

2021-04-16 13:08 UTC, RensAlthuis commented
I've been running with this for a day now and all seems good. Thanks a lot! I really appreciate the help.

2021-04-16 13:09 UTC, merged